# Generated by Django 3.2.4 on 2021-06-30 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210630_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=80, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Full name'),
        ),
    ]
