# Generated by Django 3.2.4 on 2021-07-09 08:32

from django.db import migrations, models
import main.validators
import utils.file_storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_storage.avatar_property_avatar_path, validators=[main.validators.validate_avatar_max_size], verbose_name='Avatar image'),
        ),
    ]
