# Generated by Django 3.2.4 on 2021-07-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_service_user'),
        ('users', '0009_user_bio'),
    ]

    operations = [
    ]
