# Generated by Django 3.2.4 on 2021-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_0009_add_service_user_0009_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Experience'),
        ),
    ]
