# Generated by Django 3.2.4 on 2021-07-23 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_favoriterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cooking_philosophy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=3, verbose_name='Cooking Philosophy'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_cooking_mission',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=3, verbose_name='Personal Cooking Mission'),
        ),
        migrations.AddField(
            model_name='user',
            name='source_of_inspiration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=3, verbose_name='Source of Inspiration'),
        ),
    ]
