# Generated by Django 3.2.4 on 2021-07-23 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.validators
import utils.file_storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210723_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name')),
                ('file', models.ImageField(upload_to=utils.file_storage.role_model_image_file_path, validators=[main.validators.validate_images_file_max_size], verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
