# Generated by Django 3.2.4 on 2021-08-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0036_alter_savedrecipe_recipe'),
        ('users', '0014_rolemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='recipe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to='recipe.recipe'),
        ),
    ]
