# Generated by Django 3.2.4 on 2021-08-06 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0038_alter_ingredient_quantity'),
        ('users', '0015_alter_favoriterecipe_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViewHistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('recipe', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_views', to='recipe.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
