# Generated by Django 3.2.4 on 2021-08-09 15:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userviewhistoryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommended_recipes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None, verbose_name='Recipes'),
        ),
    ]
