# Generated by Django 3.2.4 on 2021-08-12 08:38

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_recommended_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.AlterField(
            model_name='user',
            name='recommended_recipes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None, verbose_name='Recommended recipes'),
        ),
        migrations.CreateModel(
            name='WorkExperienceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
