# Generated by Django 3.2.4 on 2021-08-12 08:38

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210812_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Experience'),
        ),
    ]
