# Generated by Django 3.2.4 on 2021-08-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_revert_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkExperienceRecord',
        ),
    ]
