# Generated by Django 3.2.4 on 2021-08-16 08:33

import django.contrib.postgres.fields
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_delete_workexperiencerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cooking_philosophy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=users.models.User.get_list_default, null=True, size=3, verbose_name='Cooking Philosophy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_cooking_mission',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=users.models.User.get_list_default, null=True, size=3, verbose_name='Personal Cooking Mission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='source_of_inspiration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=users.models.User.get_list_default, null=True, size=3, verbose_name='Source of Inspiration'),
        ),
    ]
