# Generated by Django 3.2.4 on 2021-08-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_workexperiencerecord_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Users Statistics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
