# Generated by Django 3.2.4 on 2021-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
