# Generated by Django 3.2.4 on 2021-07-01 14:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('cooking_time', models.DurationField(verbose_name='cooking time')),
                ('cuisines', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'American'), (2, 'Chinese'), (3, 'Continental'), (4, 'Cuban'), (5, 'French'), (6, 'Greek'), (7, 'Indian'), (8, 'Indonisian'), (9, 'Italian'), (10, 'Japanese'), (11, 'Korean'), (12, 'Libanese'), (13, 'Malyasian'), (14, 'Mexican'), (15, 'Spanish'), (16, 'Thai'), (17, 'Moracon'), (18, 'Turkish')]), null=True, size=None, verbose_name='cuisines')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Dessert'), (5, 'Beverage'), (6, 'Appetizer'), (7, 'Salad'), (8, 'Bread')]), null=True, size=None, verbose_name='categories')),
                ('cooking_method', models.IntegerField(choices=[(1, 'Broiling'), (2, 'Grilling'), (3, 'Roasting'), (4, 'Baking'), (5, 'Sauteing'), (6, 'Poaching'), (7, 'Simmering'), (8, 'Boiling'), (9, 'Steaming'), (10, 'Braising'), (11, 'Stewing')], default=1, verbose_name='cooking method')),
                ('cooking_skills', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Complex')], default=1, verbose_name='cooking skills')),
                ('description', models.TextField(max_length=4000)),
                ('language', models.CharField(max_length=255, verbose_name='language')),
                ('caption', models.CharField(max_length=255, verbose_name='caption')),
                ('preview_thumbnail_url', models.URLField(verbose_name='preview thumbnail URL')),
                ('preview_full_thumbnail_url', models.URLField(verbose_name='preview full thumbnail URL')),
                ('preview_mp4_url', models.URLField(verbose_name='preview mp4 URL')),
                ('preview_webm_url', models.URLField(verbose_name='preview webm URL')),
                ('status', models.IntegerField(choices=[(1, 'Not published'), (2, 'Published')], default=1, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('diet_restrictions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'None'), (1, 'Vegan'), (2, 'Vegetarian'), (3, 'Pescetarian'), (4, 'Gluten Free'), (5, 'Grain Free'), (6, 'Dairy Free'), (7, 'High Protein'), (8, 'Low Sodium'), (9, 'Low Carb'), (10, 'Paleo'), (11, 'Primal'), (12, 'Ketogenic'), (13, 'FODMAP'), (14, 'Whole 30')]), blank=True, null=True, size=None, verbose_name='diet_restrictions')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'Kilogram'), (2, 'Gram'), (3, 'Miligram'), (4, 'Ons'), (5, 'Pcs'), (6, 'Cup')], verbose_name='Unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe')),
            ],
        ),
    ]
