# Generated by Django 3.2.4 on 2021-07-02 07:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210701_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Broiling'), (2, 'Grilling'), (3, 'Roasting'), (4, 'Baking'), (5, 'Sauteing'), (6, 'Poaching'), (7, 'Simmering'), (8, 'Boiling'), (9, 'Steaming'), (10, 'Braising'), (11, 'Stewing')]), default=[1], size=None, verbose_name='Cooking methods'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Dessert'), (5, 'Beverage'), (6, 'Appetizer'), (7, 'Salad'), (8, 'Bread')]), null=True, size=None, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_skills',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Complex')], verbose_name='Cooking skills'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'American'), (2, 'Chinese'), (3, 'Continental'), (4, 'Cuban'), (5, 'French'), (6, 'Greek'), (7, 'Indian'), (8, 'Indonisian'), (9, 'Italian'), (10, 'Japanese'), (11, 'Korean'), (12, 'Libanese'), (13, 'Malyasian'), (14, 'Mexican'), (15, 'Spanish'), (16, 'Thai'), (17, 'Moracon'), (18, 'Turkish')]), null=True, size=None, verbose_name='Cuisines'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet_restrictions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'None'), (1, 'Vegan'), (2, 'Vegetarian'), (3, 'Pescetarian'), (4, 'Gluten Free'), (5, 'Grain Free'), (6, 'Dairy Free'), (7, 'High Protein'), (8, 'Low Sodium'), (9, 'Low Carb'), (10, 'Paleo'), (11, 'Primal'), (12, 'Ketogenic'), (13, 'FODMAP'), (14, 'Whole 30')]), blank=True, null=True, size=None, verbose_name='Diet restrictions'),
        ),
    ]
