# Generated by Django 3.2.4 on 2021-07-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210702_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_method',
        ),
    ]
