# Generated by Django 3.2.4 on 2021-07-02 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_remove_recipe_cooking_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Dessert'), (5, 'Beverage'), (6, 'Appetizer'), (7, 'Salad'), (8, 'Bread')]), default=[], size=None, verbose_name='Categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'American'), (2, 'Chinese'), (3, 'Continental'), (4, 'Cuban'), (5, 'French'), (6, 'Greek'), (7, 'Indian'), (8, 'Indonisian'), (9, 'Italian'), (10, 'Japanese'), (11, 'Korean'), (12, 'Libanese'), (13, 'Malyasian'), (14, 'Mexican'), (15, 'Spanish'), (16, 'Thai'), (17, 'Moracon'), (18, 'Turkish')]), default=[], size=None, verbose_name='Cuisines'),
            preserve_default=False,
        ),
    ]
