# Generated by Django 3.2.4 on 2021-07-02 09:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20210702_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.AddField(
            model_name='recipe',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Dessert'), (5, 'Beverage'), (6, 'Appetizer'), (7, 'Salad'), (8, 'Bread')]), default=[], size=None, verbose_name='Types'),
            preserve_default=False,
        ),
    ]
