# Generated by Django 3.2.4 on 2021-07-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='status',
        ),
        migrations.AddField(
            model_name='recipe',
            name='publish_status',
            field=models.IntegerField(choices=[(1, 'Not published'), (2, 'Published'), (3, 'Rejected')], default=1, verbose_name='publish status'),
        ),
    ]
