# Generated by Django 3.2.4 on 2021-07-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20210705_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(1, 'Awaiting approval'), (2, 'Approved'), (3, 'Rejected')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='publish_status',
            field=models.IntegerField(choices=[(1, 'Not published'), (2, 'Published')], default=1, verbose_name='publish status'),
        ),
    ]
