# Generated by Django 3.2.4 on 2021-07-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20210705_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(1, 'Awaiting acceptance'), (2, 'Accepted'), (3, 'Rejected')], default=1, verbose_name='status'),
        ),
    ]
