# Generated by Django 3.2.4 on 2021-07-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_recipestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Calories'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Carbohydrates'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Fats'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='proteins',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Proteins'),
        ),
    ]
