
# Generated by Django 3.2.4 on 2021-07-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_auto_20210706_1613'),
        ('recipe', '0012_auto_20210707_0845'),
    ]

    operations = [
    ]
