# Generated by Django 3.2.4 on 2021-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_reciperating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='avg_rating',
            field=models.FloatField(null=True, verbose_name='Rating'),
        ),
    ]
