# Generated by Django 3.2.4 on 2021-07-07 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_recipe_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='avg_rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
    ]
