# Generated by Django 3.2.4 on 2021-07-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20210707_1440'),
        ('recipe', '0017_auto_20210707_1114'),
    ]

    operations = [
    ]
