# Generated by Django 3.2.4 on 2021-07-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0019_recipecomment_recipecommentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preview_full_thumbnail_url',
            field=models.URLField(blank=True, null=True, verbose_name='preview full thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preview_mp4_url',
            field=models.URLField(blank=True, null=True, verbose_name='preview mp4 URL'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preview_thumbnail_url',
            field=models.URLField(blank=True, null=True, verbose_name='preview thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preview_webm_url',
            field=models.URLField(blank=True, null=True, verbose_name='preview webm URL'),
        ),
    ]
