# Generated by Django 3.2.4 on 2021-07-08 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_auto_20210708_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Likes'),
        ),
    ]
