# Generated by Django 3.2.4 on 2021-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0021_auto_20210708_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbohydrates',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fats'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='proteins',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Proteins'),
        ),
    ]
