# Generated by Django 3.2.4 on 2021-07-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0021_auto_20210708_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_skills',
            field=models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Complex')], null=True, verbose_name='Cooking skills'),
        ),
    ]
