# Generated by Django 3.2.4 on 2021-07-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_alter_recipe_cooking_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagRecipeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.tag')),
            ],
            options={
                'unique_together': {('tag', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='tags', through='recipe.TagRecipeRelation', to='recipe.Recipe'),
        ),
    ]
