# Generated by Django 3.2.4 on 2021-07-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_auto_20210713_1129'),
        ('recipe', '0023_auto_20210712_1246'),
    ]

    operations = [
    ]
