# Generated by Django 3.2.4 on 2021-07-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0024_merge_0022_auto_20210713_1129_0023_auto_20210712_1246'),
        ('recipe', '0024_savedrecipe'),
    ]

    operations = [
    ]
