# Generated by Django 3.2.4 on 2021-07-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0026_alter_savedrecipe_recipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipecommentlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipecommentlike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='recipecommentlike',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='recipelike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipelike',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipelike',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='reciperating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reciperating',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='reciperating',
            name='user',
        ),
        migrations.DeleteModel(
            name='RecipeComment',
        ),
        migrations.DeleteModel(
            name='RecipeCommentLike',
        ),
        migrations.DeleteModel(
            name='RecipeLike',
        ),
        migrations.DeleteModel(
            name='RecipeRating',
        ),
    ]
