# Generated by Django 3.2.4 on 2021-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0027_auto_20210714_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
