# Generated by Django 3.2.4 on 2021-07-22 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0031_auto_20210722_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbohydrates',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Fats'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='proteins',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Proteins'),
        ),
    ]
