# Generated by Django 3.2.4 on 2021-07-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0032_alter_recipe_cuisines'),
        ('recipe', '0032_auto_20210722_1523'),
    ]

    operations = [
    ]
