# Generated by Django 3.2.4 on 2021-07-27 09:43

import django.core.validators
from django.db import migrations, models
import main.validators
import utils.file_storage


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0033_merge_20210722_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preview_full_thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preview_mp4_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preview_thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preview_webm_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(null=True, upload_to=utils.file_storage.recipe_video_file_path, validators=[main.validators.validate_video_file_max_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_storage.recipe_thumbnail_file_path, validators=[main.validators.validate_images_file_max_size], verbose_name='Thumbnail'),
        ),
    ]
