# Generated by Django 3.2.4 on 2021-07-27 16:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.validators
import utils.file_storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0034_auto_20210727_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='video',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='video_thumbnail',
        ),
        migrations.CreateModel(
            name='RecipeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to=utils.file_storage.recipe_video_file_path, validators=[main.validators.validate_video_file_max_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Video')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to=utils.file_storage.recipe_thumbnail_file_path, validators=[main.validators.validate_images_file_max_size], verbose_name='Thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
