# Generated by Django 3.2.4 on 2021-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0034_alter_tagreciperelation_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='views_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Views'),
        ),
    ]
