# Generated by Django 3.2.4 on 2021-07-28 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0036_recipevideo_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipevideo',
            name='recipe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='recipevideo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
