# Generated by Django 3.2.4 on 2021-08-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0035_recipe_views_number'),
        ('recipe', '0037_auto_20210728_1500'),
    ]

    operations = [
    ]
