# Generated by Django 3.2.4 on 2021-08-05 15:42

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0037_auto_20210804_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(validators=[main.validators.validate_decimals]),
        ),
    ]
