# Generated by Django 3.2.4 on 2021-08-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0037_auto_20210728_1500'),
        ('recipe', '0038_alter_ingredient_quantity'),
    ]

    operations = [
    ]
