# Generated by Django 3.2.4 on 2021-08-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0038_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
