# Generated by Django 3.2.4 on 2021-08-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0040_auto_20210820_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='main_image',
            field=models.BooleanField(default=False),
        ),
    ]
