# Generated by Django 3.2.4 on 2021-08-02 16:51

from django.db import migrations, models
import main.validators
import utils.file_storage


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0040_auto_20210802_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='new_file',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_storage.recipe_new_image_file_path, validators=[main.validators.validate_images_file_max_size], verbose_name='file'),
        ),
    ]
