# Generated by Django 3.2.4 on 2021-08-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0041_alter_recipestep_description'),
        ('recipe', '0041_recipeimage_main_image'),
    ]

    operations = [
    ]
