# Generated by Django 3.2.4 on 2021-08-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0036_alter_savedrecipe_recipe'),
        ('recipe', '0041_recipeimage_new_file'),
    ]

    operations = [
    ]
