# Generated by Django 3.2.4 on 2021-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0042_merge_20210825_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
