# Generated by Django 3.2.4 on 2021-08-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0043_alter_recipestep_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
