# Generated by Django 3.2.4 on 2021-08-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0044_alter_recipe_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='language',
        ),
    ]
