# Generated by Django 3.2.4 on 2021-08-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0046_auto_20210827_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
