# Generated by Django 3.2.4 on 2021-09-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0039_merge_20210806_1118'),
        ('recipe', '0048_alter_recipe_diet_restrictions'),
    ]

    operations = [
    ]
