# Generated by Django 3.2.4 on 2021-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0050_alter_recipevideo_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
