# Generated by Django 3.2.4 on 2021-09-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0042_merge_20210803_1535'),
        ('recipe', '0051_recipe_is_parsed'),
    ]

    operations = [
    ]
