# Generated by Django 3.2.4 on 2021-09-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0052_merge_0042_merge_20210803_1535_0051_recipe_is_parsed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='file',
            new_name='old_file',
        ),
        migrations.RenameField(
            model_name='recipeimage',
            old_name='new_file',
            new_name='file',
        )
    ]
