# Generated by Django 3.2.4 on 2021-09-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0053_rename_new_file_to_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='old_file',
        ),
    ]
