# Generated by Django 3.2.4 on 2021-10-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0054_remove_recipeimage_old_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='order_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
