# Generated by Django 3.2.4 on 2021-07-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharesCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Quantity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViewsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Quantity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField()),
                ('date', models.DateField(verbose_name='Day')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_records', to='contenttypes.contenttype')),
                ('shares_counter', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stat_record', to='stats.sharescounter', verbose_name='Shares counter')),
                ('views_counter', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stat_record', to='stats.viewscounter', verbose_name='Views counter')),
            ],
            options={
                'unique_together': {('date', 'content_type', 'object_id')},
            },
        ),
    ]
