# Generated by Django 3.2.4 on 2021-07-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_statrecord_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharescounter',
            options={'ordering': ['count']},
        ),
        migrations.AlterModelOptions(
            name='viewscounter',
            options={'ordering': ['count']},
        ),
    ]
