# Generated by Django 3.2.4 on 2021-07-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210727_0858'),
        ('stats', '0003_auto_20210728_1246'),
    ]

    operations = [
    ]
