version: "3.9"

networks:
  proxy: # docker network create --driver=overlay --internal=false --attachable proxy
    driver: overlay
    attachable: true
    internal: false
    name: proxy

volumes:
  static_volume:
  media_volume:

services:
  main_api:
    image: ${MAIN_IMAGE}
    restart: always
    container_name: server-api
    networks:
      - proxy
    env_file:
      - /data/.server.env
    volumes:
      - media_volume:/usr/src/app/media
      - static_volume:/usr/src/app/static
    command: gunicorn -b 0.0.0.0:80 --workers=${GUNICORN_WORKERS_PER_NODE:-4} --timeout 120 --log-level=info --log-file=- main.wsgi:application
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.main_api.entrypoints=websecure
      - traefik.http.routers.main_api.rule=Host(`${API_DOMAIN}`)
      - traefik.http.routers.main_api.tls=true
      - traefik.http.routers.main_api.tls.certresolver=letsencrypt
      - traefik.http.routers.main_api.service=main_api_service
      - traefik.http.services.main_api_service.loadbalancer.server.port=80
  main_api_proxy:
    image: nginx:1.19.2
    networks:
      - proxy
    command: nginx -c /data/conf/nginx.conf
    volumes:
      - ./main_admin_proxy/nginx.conf:/data/conf/nginx.conf:ro
      - ./main_admin_proxy/conf.d:/data/conf.d:ro
      - media_volume:/usr/src/app/media
      - static_volume:/usr/src/app/static
    depends_on:
      - main_admin
    healthcheck:
      test: service nginx status || exit 1
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.main_admin_static.entrypoints=websecure
      - traefik.http.routers.main_admin_static.rule=Host(`admin.${MAIN_DOMAIN}`) && PathPrefix(`/media`, '/static')
      - traefik.http.routers.main_admin_static.tls=true
      - traefik.http.routers.main_admin_static.tls.certresolver=letsencrypt
      - traefik.http.routers.main_admin_static.service=main_admin_static_service
      - traefik.http.services.main_admin_static_service.loadbalancer.server.port=80
