# Generated by Django 3.2.4 on 2021-07-05 15:02

from django.db import migrations, models
import main.validators
import utils.file_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.file_storage.banner_image_file_path, validators=[main.validators.validate_images_file_max_size], verbose_name='Image')),
            ],
        ),
    ]
