# Generated by Django 3.2.4 on 2021-07-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='filename',
            field=models.CharField(blank=True, help_text='Specify name "banner1.png", "banner2.png", "banner3.png" for banner to automatically appear on the main page', max_length=255, null=True),
        ),
    ]
