# Generated by Django 3.2.4 on 2021-07-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_homepagepinnedrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='filename',
        ),
    ]
