# Generated by Django 3.2.4 on 2021-07-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0033_merge_20210722_1537'),
        ('site_settings', '0008_alter_parserdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_recipe', to='recipe.recipe')),
            ],
        ),
    ]
