# Generated by Django 3.2.4 on 2021-07-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_featuredrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserdata',
            name='initial_run',
            field=models.BooleanField(default=True),
        ),
    ]
