# Generated by Django 3.2.4 on 2021-07-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_parserdata_initial_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parserdata',
            name='initial_run',
        ),
        migrations.RemoveField(
            model_name='parserdata',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='parserdata',
            name='total_results',
        ),
    ]
