# Generated by Django 3.2.4 on 2021-08-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_auto_20210729_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserdata',
            name='added_recipes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='parserdata',
            name='not_added_recipes',
            field=models.TextField(default=''),
        ),
    ]
