# Generated by Django 3.2.4 on 2021-08-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0013_parserdata_checked_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserdata',
            name='added_recipes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='parserdata',
            name='not_added_recipes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
