# Generated by Django 3.2.4 on 2021-09-16 08:10

from django.db import migrations, models
import main.validators
import utils.file_storage


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0014_auto_20210813_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.file_storage.block_image_file_path, validators=[main.validators.validate_images_file_max_size], verbose_name='Image')),
                ('text', models.TextField(max_length=1000)),
                ('change_time', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
