# Generated by Django 3.2.4 on 2021-09-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0015_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='change_time',
            field=models.PositiveIntegerField(default=2, verbose_name='Change time (sec)'),
        ),
    ]
