# Generated by Django 3.2.4 on 2021-09-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0017_alter_block_change_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='button',
            field=models.CharField(blank=True, choices=[('', 'Empty'), ('chef', 'Chef'), ('foodie', 'Foodie')], default='', max_length=25, verbose_name='button'),
        ),
    ]
