# Generated by Django 3.2.4 on 2021-09-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0018_block_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='button',
            field=models.CharField(blank=True, choices=[('', 'Empty'), ('chef', 'Chef'), ('foodie', 'Foodie')], default='', max_length=25, verbose_name='Button'),
        ),
    ]
