# Generated by Django 3.2.4 on 2021-07-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'recipe'), ('model', 'recipe')), models.Q(('app_label', 'chef_pencils'), ('model', 'chefpencilrecord')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'recipe'), ('model', 'recipe')), on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'recipe'), ('model', 'recipe')), models.Q(('app_label', 'chef_pencils'), ('model', 'chefpencilrecord')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='contenttypes.contenttype'),
        ),
    ]
