# Generated by Django 3.2.4 on 2021-07-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210714_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='is_dislike',
            field=models.BooleanField(default=False),
        ),
    ]
