# Generated by Django 3.2.4 on 2021-08-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_commentlike_is_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
