# Generated by Django 3.2.4 on 2021-07-14 14:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.validators
import utils.file_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefPencilRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(upload_to=utils.file_storage.chef_pencil_image_file_path, validators=[main.validators.validate_images_file_max_size], verbose_name='Image ')),
                ('html_content', models.TextField()),
                ('avg_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ChefPencil Record',
                'verbose_name_plural': 'ChefPencil Records',
            },
        ),
    ]
