# Generated by Django 3.2.4 on 2021-07-15 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.validators
import utils.file_storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chef_pencils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefpencilrecord',
            name='image',
            field=models.ImageField(upload_to=utils.file_storage.chef_pencil_image_file_path, validators=[main.validators.validate_images_file_max_size], verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=utils.file_storage.chef_pencil_image_file_path, validators=[main.validators.validate_images_file_max_size], verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
