# Generated by Django 3.2.4 on 2021-07-15 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chef_pencils', '0002_auto_20210715_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='chefpencil_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chef_pencils.chefpencilrecord'),
        ),
        migrations.AlterField(
            model_name='chefpencilrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefpencil_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
