# Generated by Django 3.2.4 on 2021-09-16 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chef_pencils', '0003_auto_20210715_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='ChefPencilImage',
        ),
    ]
