# Generated by Django 3.2.4 on 2021-09-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pencils', '0004_rename_attachment_chefpencilimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefpencilimage',
            name='main_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chefpencilimage',
            name='chefpencil_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chef_pencils.chefpencilrecord'),
        ),
    ]
