# Generated by Django 3.2.4 on 2021-09-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pencils', '0005_auto_20210916_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefpencilimage',
            name='user',
        ),
    ]
