# Generated by Django 3.2.4 on 2021-09-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pencils', '0006_remove_chefpencilimage_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefpencilimage',
            options={'verbose_name': "Chef's Pencil image", 'verbose_name_plural': "Chef's Pencil images"},
        ),
        migrations.AlterModelOptions(
            name='chefpencilrecord',
            options={'verbose_name': "Chef's Pencil record", 'verbose_name_plural': "Chef's Pencil records"},
        ),
    ]
