# Generated by Django 3.2.4 on 2021-09-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pencils', '0007_auto_20210916_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefpencilimage',
            options={'verbose_name': "Chef's Pencil Image", 'verbose_name_plural': "Chef's Pencil Images"},
        ),
        migrations.AlterModelOptions(
            name='chefpencilrecord',
            options={'verbose_name': "Chef's Pencil Record", 'verbose_name_plural': "Chef's Pencil Records"},
        ),
    ]
