# Generated by Django 3.2.4 on 2021-09-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pencils', '0009_chefpencilrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefpencilrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
