# Generated by Django 3.2.4 on 2021-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pencils', '0010_chefpencilrecord_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefPencilCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
