# Generated by Django 3.2.4 on 2021-09-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pencils', '0012_chefpencilrecord_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefpencilcategory',
            options={'verbose_name': "Chef's Pencil Category", 'verbose_name_plural': "Chef's Pencil Categorys"},
        ),
    ]
