# Generated by Django 3.2.4 on 2021-09-27 09:05

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    This migration will add service User to hold recipes from API
    """

    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ChefPencilCategory = apps.get_model("chef_pencils", "ChefPencilCategory")
    db_alias = schema_editor.connection.alias

    ChefPencilCategory.objects.using(db_alias).get_or_create(title='General')


def reverse_func(apps, schema_editor):
    """
    Delete service user
    """

    ChefPencilCategory = apps.get_model("chef_pencils", "ChefPencilCategory")
    db_alias = schema_editor.connection.alias

    try:
        ChefPencilCategory.objects.using(db_alias).get(
            title='General',
        ).delete()
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pencils', '0013_alter_chefpencilcategory_options'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]