# Generated by Django 3.2.4 on 2021-09-27 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chef_pencils', '0014_add_general_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedChefPencilRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef_pencil_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_chef_pencil_records', to='chef_pencils.chefpencilrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_chef_pencil_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'chef_pencil_record')},
            },
        ),
    ]
