# Generated by Django 3.2.4 on 2021-10-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pencils', '0017_chefpencilimage_order_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefpencilrecord',
            name='image',
        ),
    ]
