# Generated by Django 3.2.4 on 2021-10-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pencils', '0018_remove_chefpencilrecord_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefpencilrecord',
            name='category',
        ),
        migrations.CreateModel(
            name='ChefPencilRecordCategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='chef_pencils.chefpencilcategory')),
                ('chefpencil_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='chef_pencils.chefpencilrecord')),
            ],
        ),
        migrations.AddField(
            model_name='chefpencilcategory',
            name='chefpencil_records',
            field=models.ManyToManyField(through='chef_pencils.ChefPencilRecordCategoryLink', to='chef_pencils.ChefPencilRecord'),
        ),
    ]
