# Generated by Django 3.2.4 on 2021-10-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pencils', '0019_auto_20211006_1006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chefpencilrecordcategorylink',
            unique_together={('category', 'chefpencil_record')},
        ),
    ]
