# Generated by Django 3.2.4 on 2021-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New user greeting'), (2, 'Recipe created. Awaiting approval'), (3, 'Recipe status changed'), (4, 'New comments in your recipe')], verbose_name='code'),
        ),
    ]
