# Generated by Django 3.2.4 on 2021-09-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New user greeting'), (2, 'Recipe created. Awaiting approval'), (3, 'Recipe status changed'), (4, 'New comments in your recipe'), (5, 'Chef Pencil Record created. Awaiting approval'), (6, 'Chef Pencil Record status changed'), (7, 'New comments in your Chef Pencil Record')], verbose_name='code'),
        ),
    ]
